apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson-github-com
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJkWE5sY201aGJXVTZjR0Z6YzNkdmNtUT0iCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
